# Generated by Django 3.1 on 2023-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/default.jpeg', upload_to='profile_image'),
        ),
    ]
