# Generated by Django 3.1 on 2023-07-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
    ]
